### ISSUE TITLE
Coding guidelines

### ISSUE THREAD

**Issue by itslewiswatson** [mtadayz/MTADayZ#51]
For every open-source project, I believe it's a good idea to have some sort of coding guideline established. Every coder seems to have a different coding style, both in their logic and in their syntax. I for example, I like to avoid having lots of nested if-statements and I tab-indent. Others may not follow this same style. That causes messy code over time if we have a lot of different styles conflicting.

Having the same coding style (defining functions as opposed to inline functions in the event handler, or spaces between each argument within parenthesis, for example) throughout all your code makes it easier to maintain, and it looks nicer.

**Comment by Renkon** [comment]
Considering that, I personally would recommend that:

Regarding identation, 4 spaces (tab) would be the most suitable.
Functions and variables should be named with lower-case letters (and
upper-case letters for beginning of words). Ex: getZombieHealth,
findNextPlayer, etc.
As for parenthesis statements like if () and so on, I'd prefer that we
leave one space before and after operands. if (a == b) then.. and so on
since it's easier to comprehend than if (a==b), or at least more
reading-friendly.
Trying to name variables so they are self-explaining would be also a key.
Using local variables as far as you can would be ideal too.

If there are any more suggestions post them below.

2015-10-26 8:24 GMT-03:00 nokizorque notifications@github.com:

**Comment by 0xCiBeR** [comment]
As for variables, we should use lowerCamelCase https://es.wikipedia.org/wiki/CamelCase
Indentation as follows:
Function declaration - 0 Tab
First If Statement - 1 Tab
Rest If Statements - Last Tab + 1
For if Statements - Last Tab + 1
Global Variables - 0 Tab
Table Values - 0 Tab(But line per line basis)

**Comment by 0xCiBeR** [comment]
I'm closing this as i think it's clear on how to code.
