### ISSUE TITLE
Backpack size changing does not work...

### ISSUE THREAD

**Issue by Risusama** [mtadayz/MTADayZ#54]
Not sure if this an issue, but I thought I would ask it here, because of mtadayz site being down, and L has been active here, so...

So... I have tried to change backpack size before, and after the update that is supposed to make it easier.
But both times, it did not work. Game loads properly, works good, I can't find any errors, but backpack sizes do not change.
## EDIT

I have now tried it on Windows and Debian linux. Both seem not to work.

If someone is willing to at least try and help me, just respond here.

And sorry for asking help from here, I know this might not be the right place...

Thank you!
- Christian

**Comment by 1B0Y** [comment]
If I recall from a few months ago when I was working on the project, the backpack size was hard coded for a reason. The backpack would bug if it exceeded the set inventory size because of how it was being rendered, resulting in debug being spammed and the client potentially freezing up.

[Correct me if wrong. I haven't kept up-to-date]
